// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package schema generated by go-bindata.// sources:
// delivery/graphql/schema/query.graphql
// delivery/graphql/schema/mutation.graphql
// delivery/graphql/schema/type/job.graphql
package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _deliveryGraphqlSchemaQueryGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x44\xcb\xc1\xaa\xc2\x30\x10\x85\xe1\x7d\xa1\xef\x70\x42\x37\xf7\xbe\x42\xd6\x22\x58\xdc\x48\x97\xe2\xa2\xa9\x43\x13\x89\x19\xe9\x4c\x90\x20\xbe\xbb\xa4\x54\xdc\x1d\x0e\xff\xa7\xe5\x41\x38\x65\x5a\x0a\x5e\x6d\x03\x74\x38\x06\x51\x8c\x31\xe2\xc6\x4e\x10\x12\xd4\x13\xa4\x88\xd2\xbd\x06\x3d\x3b\xb1\x38\xf7\xec\xcc\xc5\xb4\x4d\xbd\x3a\xec\x49\x27\x8f\x11\x12\xd2\x1c\xa9\x4a\xb8\x82\xc3\x6e\x03\x7f\xe1\x6a\x31\xe8\x12\xd2\x6c\xfe\x2d\x7a\x76\x5f\x38\x78\x7e\xae\xb9\xe8\xa8\x59\x30\x71\x4e\x2a\x1b\x1b\xd6\xcf\xfe\xa6\x69\x9b\xf7\x67\x00\x45\x42\x86\x23\xb1\x00\x00\x00")

func deliveryGraphqlSchemaQueryGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_deliveryGraphqlSchemaQueryGraphql,
		"delivery/graphql/schema/query.graphql",
	)
}

func deliveryGraphqlSchemaQueryGraphql() (*asset, error) {
	bytes, err := deliveryGraphqlSchemaQueryGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "delivery/graphql/schema/query.graphql", size: 177, mode: os.FileMode(438), modTime: time.Unix(1789030599, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _deliveryGraphqlSchemaMutationGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\x8e\xb1\x4e\xc4\x40\x0c\x44\xfb\xfd\x8a\xc9\xd1\xdc\x49\x50\xc0\x75\x69\x11\x4d\x24\x68\x4e\x54\x88\xc2\xbb\x18\xb2\x21\xd8\xb0\x6b\x2b\x3a\x21\xfe\x1d\xad\x80\x13\x29\x47\xf6\x9b\x79\x76\x7c\x67\xdc\xba\x91\x65\x15\x7c\x06\xe0\x0c\xd7\x85\xc9\x18\x77\xbc\x60\xd0\x18\x80\x1b\xf9\x70\x76\xde\x1a\xd5\xd7\x1e\x07\x2b\x59\x5e\xba\x5d\xdf\xae\x5d\xf8\x8f\xec\x31\x69\xac\x48\x2a\xc9\x4b\x61\xb1\xf9\x18\x80\x43\x7e\xf3\xd9\x48\x58\xbd\xfe\x74\x0f\x1a\xb7\x93\xc6\xcb\x53\xd9\x79\x03\xaf\xd6\x71\x7f\x8a\xbb\x1e\x0f\x6d\xeb\x71\xbd\x46\xed\x0b\x4b\xb6\x11\xcd\x0c\x1b\x97\x6a\x14\x67\xbe\x98\x34\x6e\x60\x23\x19\x9e\x29\xcf\x15\xb6\xe4\xc4\xb0\x91\x05\xd5\x53\x62\x7e\xaa\x7f\x5e\x64\x7c\xff\x8b\x0d\x1a\x7b\x0c\x1a\xbb\xf0\x15\xbe\x07\x00\x69\x0c\x26\x28\x18\x01\x00\x00")

func deliveryGraphqlSchemaMutationGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_deliveryGraphqlSchemaMutationGraphql,
		"delivery/graphql/schema/mutation.graphql",
	)
}

func deliveryGraphqlSchemaMutationGraphql() (*asset, error) {
	bytes, err := deliveryGraphqlSchemaMutationGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "delivery/graphql/schema/mutation.graphql", size: 280, mode: os.FileMode(438), modTime: time.Unix(1789036094, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _deliveryGraphqlSchemaTypeJobGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\x8c\x41\x0a\xc2\x30\x10\x45\xd7\x1d\x98\x3b\xfc\x5c\x23\x37\xa8\xdb\x9e\x20\x9a\xb1\x04\xdb\x69\x68\x7e\x17\x22\xbd\xbb\x28\x14\xeb\xf2\x3d\x1e\x8f\xcf\x6a\xb8\x2c\x57\xbc\x54\xba\x92\x23\x06\xae\xc5\xc7\xa0\xd2\x31\xb5\xc7\x99\x1b\x13\xb7\x76\x36\x89\xb4\xb9\xb2\x45\xf4\xce\xa0\xb2\xab\xa8\x1c\xc7\xe1\x9b\x7f\xbe\x40\x35\xcf\xc5\xc7\xa3\x03\xd6\xcd\xfd\x4f\xdc\x53\x99\x2c\xff\xf8\xb6\xcc\x75\x32\x5a\x8e\xe8\x9d\x41\x65\x7f\x0f\x00\xa4\xd0\xf3\x9a\xaa\x00\x00\x00")

func deliveryGraphqlSchemaTypeJobGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_deliveryGraphqlSchemaTypeJobGraphql,
		"delivery/graphql/schema/type/job.graphql",
	)
}

func deliveryGraphqlSchemaTypeJobGraphql() (*asset, error) {
	bytes, err := deliveryGraphqlSchemaTypeJobGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "delivery/graphql/schema/type/job.graphql", size: 170, mode: os.FileMode(438), modTime: time.Unix(1789030599, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"delivery/graphql/schema/query.graphql":    deliveryGraphqlSchemaQueryGraphql,
	"delivery/graphql/schema/mutation.graphql": deliveryGraphqlSchemaMutationGraphql,
	"delivery/graphql/schema/type/job.graphql": deliveryGraphqlSchemaTypeJobGraphql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"delivery": &bintree{nil, map[string]*bintree{
		"graphql": &bintree{nil, map[string]*bintree{
			"schema": &bintree{nil, map[string]*bintree{
				"mutation.graphql": &bintree{deliveryGraphqlSchemaMutationGraphql, map[string]*bintree{}},
				"query.graphql":    &bintree{deliveryGraphqlSchemaQueryGraphql, map[string]*bintree{}},
				"type": &bintree{nil, map[string]*bintree{
					"job.graphql": &bintree{deliveryGraphqlSchemaTypeJobGraphql, map[string]*bintree{}},
				}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
